### PR TITLE
Fix computing time for clock_nanosleep (Fix #357)

### LINKED ISSUE #357: RealtimeSynchronize block "clock_nanosleep" error on Linux
Sporadically there is an error when using  `Blocks.OperatingSystem.RealtimeSynchronize` on Linux. The simulation exists with the message `MDDRealtimeSynchronize.h: clock_nanosleep(..) failed`.

The reason for this is that 
https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/blob/b2fa5d7a55de4342a29ca68f7c18c9edb1c100bf/Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h#L960
fails due to an invalid `t_abs` (negative `t_abs.tv_nsec`). The cause is further up in 
https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/blob/b2fa5d7a55de4342a29ca68f7c18c9edb1c100bf/Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h#L928
where it was overlooked that `timespec_subtract(...)` may modify its third argument for perfomring a carry.

### PR DESCRIPTION
**Pull request by bernhard-thiele**

### CODE REVIEW

File: Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h [hunk 1]
```diff
@@ -959,15 +963,16 @@ DllExport void MDD_RTSyncSynchronize(void * rtSyncObj, double simTime, double sc
         /* wait until (scaled) simulation time == real-time */
         ret = clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &t_abs, NULL);
         if (ret) {
-            ModelicaError("MDDRealtimeSynchronize.h: clock_nanosleep(..) failed\n");
+            ModelicaFormatError("MDDRealtimeSynchronize.h: clock_nanosleep(..) failed\n");
```
Comment (beutlich) [inline Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h:966]: That change seems undesired, since the first argument is not a format string.

File: Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h [hunk 2]
```diff
@@ -875,6 +875,8 @@ DllExport void MDD_RTSyncDestructor(void* rtSyncObj) {
     }
 }
 
+#include <stdint.h>
```
Comment (beutlich) [inline Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h:878]: That change seems either independent of the actual change or undesired.

File: Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h (hunk 1 above)
Comment (bernhard-thiele) [reply Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h:966]: Yes, I've had quite some "printf" debugging before finding the cause and this as well as the line below are artifacts from the debugging... I will remove it.

File: Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h (hunk 2 above)
Comment (bernhard-thiele) [reply Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h:878]: as above

**Comment by bernhard-thiele** [comment]
Thanks for checking
